### ISSUE TITLE
ConTeXt build failing

### ISSUE THREAD

**Issue by yigothu** [flyx/TeX.novaextension#2]
It fails with log:

```
/Users/name/Library/Application Support/Nova/Extensions/org.flyx.tex/Scripts/run_context.sh: line 21: context: command not found
```

I am using the latest version of Context (LMTX). I have checked that running both

```
context Hello-world.tex
```

and

```
context --luatex Hello-world.tex
```

from the terminal work (the latter is forcing ConTeXt  to use the older version mkIV instead).

**Comment by flyx** [comment]
The `context` utility must be in your `PATH` inside a `/bin/sh` session. MacTeX does this by adding a file `/etc/paths.d/TeX` with the content

    /Library/TeX/texbin

How did you install ConTeXt?

**Comment by yigothu** [comment]
Via the instructions on ConTeXtGarden:

https://wiki.contextgarden.net/Installation

**Comment by flyx** [comment]
The problem is that Nova executes the ConTeXt build in a non-login shell, which means that none of the files `~/.bashrc`, `~/.bash_profile` or `~/.profile` are executed.

A workaround would be to do

```
echo "...instructions..." | sudo tee /etc/paths.d/ConTeXt
```

with `...instructions...` being what is described in the manual you linked. You probably need to log out and in again for that to take effect afterwards.

However, this is generally not a good solution since the ConTeXt instructions direct you to install it in your user directory and therefore the path configuration should be per user.

This extension should do one (or more) of the following:

 * call the shell with `--login` so that `~/.profile` is executed and can be used to define the ConTeXt path
 * try to find the absolute path to the ConTeXt bin folder and just use that
 * let the user enter the ConTeXt installation prefix

I will muse about that for a bit and will provide a solution with the next release. In the meantime, you can use the workaround I described.

**Comment by yigothu** [comment]
Thanks, the workaround solves it. Alternatively if I do a systemwide installation of ConTeXtLMTX that also works.

**Comment by flyx** [comment]
The new version I just released contains the following features addressing this problem:

 * probes your default shell (i.e. the one in `$SHELL`) with `--login` (to load the shell-specific scripts that modify your PATH) for `context` (via `which context`) and uses that.
 * both the global extension preferences and the workspace preferences allow you to explicitly set the path to `context`, which will override the probed path (with workspace taking precedence).

**Comment by yigothu** [comment]
Thank you for the update. I am still getting the same error however. 

Setting the path to ConTeXt from the terminal:

![2021-11-14 at 10 53 39 Screenshot](https://user-images.githubusercontent.com/52865181/141676206-293c8775-ecb7-4597-9fc7-265302f735b2.png)

Adding the path in TeXSuite

![2021-11-14 at 07 10 07 Screenshot](https://user-images.githubusercontent.com/52865181/141669888-584a2bd7-825b-44f1-beb1-46c22836427a.png)

Fails with

<img width="960" alt="2021-11-14 at 07 11 08 Screenshot" src="https://user-images.githubusercontent.com/52865181/141669906-37f00d43-fd4f-4d63-bad0-91ecd2a95fa3.png">

**Comment by flyx** [comment]
Sadly this is hard to test for setups different than mine, I'll have a look again

**Comment by yigothu** [comment]
If there's anything I can do to help test, let me know! Sorry for the trouble.

**Comment by flyx** [comment]
I pushed a commit that fixed multiple things – it would be great if you could test if this fixes your problem or, what I assume, gives you a more relevant error message. For this, you need to:

 * disable the TeX extension in Nova
 * enable Extension Development in Nova Settings->General
 * clone my repo, open it in Nova and in the Extensions menu, click *Activate Project as Extension*
 * also in that menu, click *Show Extension Console*
 * open a new workspace with your ConTeXt code and try to build it
 * the console may give you some additional information

**Comment by yigothu** [comment]
I confirm the new commit fixes the problem on my machine! Thank you so much :)

**Comment by flyx** [comment]
Great, thanks for testing! I pushed a new release containing this fix.
